### ISSUE TITLE
Collect tests by building

### ISSUE THREAD

**Issue by beefon** [dropbox/hypershard-ios#1]
> In benchmarks, Hypershard takes, on average, under 0.06s per collection of tests from Dropbox and Paper iOS apps, down from roughly ~15 minutes it tooks us to collect tests by building of the individual apps.

How do you collect tests by building the apps? By dumping class and method names from resulting build artifacts and parsing them? Or is there a hidden Xcode setting, or any output that Xcode build system generates when it builds test bundles?

**Comment by bogo** [comment]
We got rid of this a while back, so I'm a bit hazy on the details. I believe it actually involved attempting to run the UI tests and inspecting the [`tests`](https://developer.apple.com/documentation/xctest/xctestsuite/1500631-tests) property on the `XCTestSuite.default`. Hope this helps! 👍

**Comment by beefon** [comment]
Thanks!
